_BASE_: "../base-finetune.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "imagenet"
  DATAPATH: "../../imagenet1k"  #TODO: need to specify here
  NUMBER_CLASSES: 1000
  MULTILABEL: False
  FEATURE: "sup_vitb16_imagenet21k"  # need to tune
  NO_TEST: True
MODEL:
  TYPE: "vit"
  MODEL_ROOT: "checkpoints"
SOLVER:
  BASE_LR: 0.0375
  WEIGHT_DECAY: 0.001
